### ISSUE TITLE
Missing zmq.hpp

### ISSUE THREAD

**Issue by fabien-avt** [Opendigitalradio/ODR-SourceCompanion#1]
The file src/zmq.hpp is included by odr-sourcecompanion.cpp
src/odr-sourcecompanion.cpp:27:19: fatal error: zmq.hpp: No such file or directory
After providing this file (got from another odr repository), the make process is completed.

**Comment by mpbraendli** [comment]
Thanks for noticing! It's fixed in 'next' with 097cd2287d08743558320f3f08c09fa3e5b7a60b
