### ISSUE TITLE
Problems compiling

### ISSUE THREAD

**Issue by ea5iva** [Opendigitalradio/ODR-SourceCompanion#2]
Hi, I get this errors when I run make on a Debian GNU/Linux 12 system

I've installed all the dependencies and required packages.

CXX      lib/odr_sourcecompanion-ClockTAI.o
lib/ClockTAI.cpp: In function ‘std::string load_bulletin_from_file(const char*)’:
lib/ClockTAI.cpp:262:13: error: ‘strerror’ was not declared in this scope; did you mean ‘hstrerror’?
  262 |             strerror(errno);
      |             ^~~~~~~~
      |             hstrerror
lib/ClockTAI.cpp:281:25: error: ‘strerror’ was not declared in this scope; did you mean ‘hstrerror’?
  281 |                         strerror(errno);
      |                         ^~~~~~~~
      |                         hstrerror
lib/ClockTAI.cpp:295:13: error: ‘strerror’ was not declared in this scope; did you mean ‘hstrerror’?
  295 |             strerror(errno);
      |             ^~~~~~~~
      |             hstrerror
lib/ClockTAI.cpp: In constructor ‘ClockTAI::ClockTAI(const std::vector<std::__cxx11::basic_string<char> >&)’:
lib/ClockTAI.cpp:317:21: warning: loop variable ‘url’ creates a copy from type ‘const std::__cxx11::basic_string<char>’ [-Wrange-loop-construct]
  317 |     for (const auto url : m_bulletin_urls) {
      |                     ^~~
lib/ClockTAI.cpp:317:21: note: use reference type to prevent copying
  317 |     for (const auto url : m_bulletin_urls) {
      |                     ^~~
      |                     &
lib/ClockTAI.cpp: In member function ‘int ClockTAI::get_valid_offset()’:
lib/ClockTAI.cpp:362:29: warning: loop variable ‘url’ creates a copy from type ‘const std::__cxx11::basic_string<char>’ [-Wrange-loop-construct]
  362 |             for (const auto url : m_bulletin_urls) {
      |                             ^~~
lib/ClockTAI.cpp:362:29: note: use reference type to prevent copying
  362 |             for (const auto url : m_bulletin_urls) {
      |                             ^~~
      |                             &
lib/ClockTAI.cpp: In member function ‘void ClockTAI::update_cache(const char*)’:
lib/ClockTAI.cpp:522:13: error: ‘strerror’ was not declared in this scope; did you mean ‘hstrerror’?
  522 |             strerror(errno);
      |             ^~~~~~~~
      |             hstrerror
lib/ClockTAI.cpp:540:21: error: ‘strerror’ was not declared in this scope; did you mean ‘hstrerror’?
  540 |                     strerror(errno);
      |                     ^~~~~~~~
      |                     hstrerror
lib/ClockTAI.cpp:554:13: error: ‘strerror’ was not declared in this scope; did you mean ‘hstrerror’?
  554 |             strerror(errno);
      |             ^~~~~~~~
      |             hstrerror
lib/ClockTAI.cpp: At global scope:
lib/ClockTAI.cpp:215:15: warning: ‘size_t fill_bulletin(char*, size_t, size_t, void*)’ defined but not used [-Wunused-function]
  215 | static size_t fill_bulletin(char *ptr, size_t size, size_t nmemb, void *ctx)
      |               ^~~~~~~~~~~~~
make[1]: *** [Makefile:912: lib/odr_sourcecompanion-ClockTAI.o] Error 1
make[1]: Leaving directory '/home/odr/ODR-mmbTools/ODR-SourceCompanion'
make: *** [Makefile:453: all] Error 2

**Comment by mpbraendli** [comment]
Does compilation of the `next` branch work? It's probably already fixed in that one.

**Comment by colisee** [comment]
Hi Matthias,

taking over @ea5iva, I confirm that the `next` branch compiles for both `bullseye`, `bookworm` and `unstable` (future trixie).

Thus, I believe you could push the changes from the `next` branch to `master` and create a new version.

**Comment by mpbraendli** [comment]
New version released!
